### ISSUE TITLE
TwoFactorAuth.org should now be 2fa.directory

### ISSUE THREAD

**Issue by joncamfield** [narwhalacademy/zebra-crossing#11]
See https://github.com/2factorauth/twofactorauth/issues/5238 for background, but the site at twofactorauth.org is now a sales page, and the directory is now at 2fa.directory

**Comment by adrawerofthings** [comment]
Thanks for the tip @joncamfield! Have implemented in the update this week. Should've done it earlier really, but kinda fell behind.
